import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <footer>
          <p className="text-center text-sm  text-gray-400 font-extralight">
            Copyright@2026. Developed by{" "}
            <Link
              className="underline"
              target="_blank"
              href={"https://github.com/icerahi"}
            >
              MD IMRAN HASAN
            </Link>
          </p>
        </footer>
      </body>
    </html>
  );
}
